### PR TITLE
Use Zbarlight as alternative to pyzbar when it's not available

### PR DESCRIPTION
**Pull request by Cheaterman**
Everything in the title - pyzbar won't work on iOS.

EDIT: FWIW this PR is rebased onto #39 - it's probably a good idea to merge both, but if that's considered problematic I can probably split them.

### CODE REVIEW

**Comment by AndreMiras** [comment]
Thanks for giving it a look and spending time on it.
I have some suggestions. To begin with, could you not rebase on the other PR so we can better focus one what you're trying to address.
Also could you take a look into the unit tests which are failing?

**Comment by Cheaterman** [comment]
@AndreMiras sure thing :-) I'll look into both, thanks for your early feedback!

**Comment by Cheaterman** [comment]
I quickly looked at the failing tests - I thought it might be a good idea to normalize the code_types as lowercase because that used to be the case, but obviously people might rely on them as they are now :-) fixing!

**Comment by Cheaterman** [comment]
Alright, tests should succeed, and I think this generally should work as intended :-)

**Review by AndreMiras — APPROVED** [review]
I think this is looking good, well done.
I wish you wrote additional tests for some of the new behaviour so nobody breaks it without noticing.
I'll merge still (and fix the linting) feel free to follow up with increase test coverage

**Comment by AndreMiras** [comment]
Made the follow up PR with tests. Also introduced a class for the cross implementation to ease testing and avoid root level logic #46

**Pull request merged**
