### PR TITLE
Garden fix - kivy_garden package isn't a thing

### PR DESCRIPTION
**Pull request by Cheaterman**
Everything in the title - kivy.garden.zbarcam works here, kivy_garden.zbarcam doesn't. Possibly the issue is on my end, but AIUI, kivy_garden isn't a thing?

This PR is rebased onto #39 and #42 - if that's an issue I'll split everything up.

Thanks in advance :-)

### CODE REVIEW

**Comment by AndreMiras** [comment]
I'm not sure I understand how this is happening as yes `kivy_garden` should be a thing and `kivy.garden` is not. Actually `kivy.garden` got deprecated some time ago, see #17

**Comment by Cheaterman** [comment]
Whoa @AndreMiras thanks a lot for the information! My incorrect inference was made when using `garden install --app zbarcam` to package the flower on Android/iOS, and it didn't seem to work with `kivy_garden` but did with `kivy.garden`... I'll look into all of this for more info, and possibly make a PR on Kivy if that's the issue. Thanks again, sorry for the noise!

**Comment by AndreMiras** [comment]
Ah yes I see, yes indeed we dropped `garden` command, now you simply `pip install zbarcam` on desktop since it's available on PyPI https://pypi.org/project/zbarcam/
And on Android as well it will be a normal pip dependency, no longer under the garden in buildozer

**Comment by Cheaterman** [comment]
Ah alright, I didn't know that was a thing! Thanks a lot for the info, I'll do as you suggested and see what happens :-)

**Pull request closed without merging**
